### ISSUE TITLE
State description in URL

### ISSUE THREAD

**Issue by alexis-thual** [arkhn/pyrog#43]
Client's URL should contain app state.
This would allow:
* refreshing pages without loosing the state
* sharing pages between authenticated users

For instance, in the source view:
* current URL: `http://0.0.0.0:1729/sources`
* desired URL: `http://0.0.0.0:1729/sources?sourceId=xxxxx&resourceId=xxxxx&attributeId=xxxx`

**Comment by saifali96** [comment]
Good idea @alexis-thual , would then we need to make `GET` requests for these?

**Comment by alexis-thual** [comment]
This would only be available in the client, so as to describe the state of the web application :slightly_smiling_face: (so no `GET` requests a priori)
I was thinking of using `query-string` to implement this: https://www.npmjs.com/package/query-string

What did you have in mind with these `GET` requests?

**Comment by saifali96** [comment]
Oh okay! Got it now. I understood that you are suggesting to change the requests/queries from `POST` to `GET` to achieve the above desired URL.

I checked the `query-string` npm package, looks really nice. But correct me if I am wrong, would we need to parse the url and then craft a custom query to be sent to the API and then render the DOM?

Because we would still need to send the queries by `POST` or whatever other request method we are using?

**Comment by alexis-thual** [comment]
This is now solved in #47!
What happens in the following: the `Navbar` component checks whether the user is on the `mapping` view. If that is the case, it looks for `search` arguments (that is to say arguments present in the url) and fetches complementary data (source name, fhir resource name, etc) from our server through a graphql request.

**Comment by saifali96** [comment]
Understood! And great work on the #47 but do you think it would be better to exclude the prettifying commits? They made the diff super big and might be difficult to debug/track in case of bugs in the future if you merge this feature and prettify the code in the same PR?

**Comment by alexis-thual** [comment]
You are absolutely right, I'll to this in the future :)
