### ISSUE TITLE
Allow multiple declarations of similar FHIR resources

### ISSUE THREAD

**Issue by Nabellaleen** [arkhn/pyrog#56]
In some cases, multiple mappings are possible for a given FHIR resource.

For example, we could map a `Observation` resource to store the `Clinical Sex` of a `Patient`, on a given column from the source database. Then map "another" `Observation` resource for `Blood Pressure` on rows from a specific table storing these values in the source database, etc.

For this purpose, we should : 

- [x] UI - Be able to add multiple resources from the same FHIR type
- [x] UI - Be able to "name" a mapped resource to differentiate it from the other resources of the same type (labelling)
- [x] DB - Store the actual `name` of resources in a `FHIR type` field, to have the `name` field dedicated to a "labelling" value
- [x] FHIRPIPE - Take this new feature into account for data migration

**Comment by alexis-thual** [comment]
@LaRiffle a PR is ready to close this ; you should be expecting breaking changes in fhir-pipe soon.
Changes are simple though:
- the `name` attribute of a `Resource` is now named `fhirResourceName`
- `instanceName` is a new attribute available in `Resource` (in order to differentiate two similar resources belonging to the same source)
